### ISSUE TITLE
runstation throws exception on termination, fails to reset terminal mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brata-hsdc/brata#22]
```
runstation throws exception when closing down in response to Ctrl-C from 
terminal.


What steps will reproduce the problem?
From a terminal command line:
1. sudo python /home/pi/brata.station/bin/runstation
2. Ctrl-C

This is the output:
----------------------------
DEBUG:station.hw:Setting Line 1 text to "Shutting down..."
DEBUG:station.hw:Display now reads "Shutting down..."[br]"    00:00:00    "
DEBUG:station.hw:Setting Line 2 text to "                "
DEBUG:station.hw:Display now reads "Shutting down..."[br]"                "
DEBUG:station.hw:Display now reads "Shutting down..."[br]"                "
DEBUG:station.hw:Stopping listening for push button monitor
DEBUG:station.connection:Stopping listening for connection manager
INFO:station.connection:Is connection manager connected? False

Pibrella exiting cleanly, please wait...
Stopping flashy things...
Stopping user tasks...
Cleaning up...
Goodbye!
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/home/pi/brata.station/bin/../station/hw.py", line 569, in run
  File "/home/pi/brata.station/bin/../station/util.py", line 105, in __exit__
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 
'tcsetattr'
-----------------------------------

It looks like the termios module object has been set to None before calling 
termios.tcsetattr() to restore the original terminal mode setting.  The result 
is that the terminal does not echo characters typed at the command prompt.  You 
can type "reset<RETURN>" to put the terminal back to a normal state.

```

Original issue reported on code.google.com by @ellerychan on 13 Nov 2014 at 4:16

**Comment by jawaad-ahmad** [comment]
Continued on brata-hsdc/brata.station#5.
